package com.lianlian.ew.open.response;

import com.lianlian.ew.open.domain.AdditionalInfo;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.io.Serializable;
import java.util.Date;
import java.util.List;


@Getter
@Setter
@ToString
public class RequestOrderDetailRes implements Serializable {
    private static final long serialVersionUID = 3992600477233528801L;


    /**
     * Unique ID created by the LianLian Global.
     */
    private String id;


    /**
     * The idempotent value generated by the client must be unique on each request.
     * Requests with the same request_id will be rejected.
     * The parameter contains a maximum of 128 characters.
     */
    private String requestId;

    /**
     * Unique identifier of the User.
     */
    private String userId;

    /**
     * The unique identifier of the Payer.
     */
    private String payerId;

    /**
     * Payer name.
     */
    private String payerName;

    /**
     * The amount to collect, main currency unit, rounded up to 2 decimal places.
     */
    private String amount;

    /**
     * The currency to collect (in three-letter ISO 4217 format).
     */
    private String currency;

    /**
     * Purpose of Request Payment.
     */
    private String purpose;

    /**
     * The ID of File Folder object.
     */
    private String fileFolderId;

    /**
     * The message to be displayed to the Payer.
     */
    private String reference;

    /**
     * Expire time for this Request Payment. Measured in milliseconds since the Unix epoch.
     */
    private Date expireTime;

    /**
     * Set of key-value pairs that you can attach the business information according to Lianlian's requirements.
     */
    private List<AdditionalInfo> additionalInfo;

    /**
     * The Request Payment status.
     */
    private String status;


//    {
//        "id": "string",
//            "request_id": "string",
//            "user_id": "string",
//            "payer_id": "string",
//            "payer_name": "string",
//            "amount": "12.23",
//            "currency": "USD",
//            "purpose": "string",
//            "file_folder_id": "2019-08-24",
//            "reference": "string",
//            "expire_time": "string",
//            "additional_info": [
//        {
//            "name": "string",
//                "value": "string"
//        }
//  ],
//        "status": "PAID"
//    }


}