package com.lianlian.ew.open.response;

import com.lianlian.ew.open.domain.AdditionalInfo;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * request pay url res
 *
 * @author xujs002
 */

@Getter
@Setter
@ToString
public class RequestPayUrlRes implements Serializable {
    private static final long serialVersionUID = -7361463104405794390L;


    /**
     * The idempotent value generated by the client must be unique on each request.
     * Requests with the same request_id will be return last Request Payment URL if exists.
     * The parameter contains a maximum of 128 characters.
     */
    private String requestId;


    /**
     * The amount to collect, main currency unit, rounded up to 2 decimal places.
     */
    private String amount;


    /**
     * The currency to collect (in three-letter ISO 4217 format).
     */
    private String currency;


    /**
     * Purpose of Request Payment.
     */
    private String purpose;


    /**
     * This is the postscript information visible to the payer.
     */
    private String reference;


    /**
     * Set of key-value pairs that you can attach the business information according to Lianlian's requirements.
     */
    private List<AdditionalInfo> additionalInfo;


    /**
     * Expire time for this Request Payment. Measured in milliseconds since the Unix epoch.
     */
    private Date expireTime;

    /**
     * The URL where the payer is redirected after he or she approves the Request Payment.
     */
    private String returnUrl;


    /**
     * The Request Payment URL for payer to pay on the Dashboard.
     */
    private String requestPaymentUrl;
}
